### ISSUE TITLE
关闭OverlayFS问题

### ISSUE THREAD

**Issue by m-coder-hue** [friendlyarm/sd-fuse_rk3566#1]
个人设备：nanopi r3s
问题描述：依据readme教程中创建不使用OverlayFS的SD卡镜像时，可以创建成功img，但刷入时设备的sys灯慢闪，LAN和WAN灯熄灭，通过路由器查看设备无法获得dhcp地址。
同时，参照[How to Install Docker on Debian/zh](https://wiki.friendlyelec.com/wiki/index.php/How_to_Install_Docker_on_Debian/zh)进行前两种方式的操作时均会导致userdata分区消失，rootfs分区扩充（通过拔出tf卡插读卡器获知），同时系统无法启动，问题与上面提到的相同
设备在官方提供的镜像刷写后可以正常使用（dhcp可以获取地址）

**Comment by lawrencetg** [comment]
尝试使用prebuilt里带-plain后辍的dtbo.img/parameter.txt，参考示例：
```
rm -f ubuntu-noble-core-arm64/userdata.img
cp -f prebuilt/dtbo-plain.img ubuntu-noble-core-arm64/dtbo.img
cp -f prebuilt/parameter-plain.txt ubuntu-noble-core-arm64/parameter.txt
./mk-emmc-image.sh ubuntu-noble-core-arm64
```

**Comment by m-coder-hue** [comment]
谢谢，这确实有效，我使用dtbo-plain.img替换了原来的dtbo.img，后重新编译，生成的debian-core的img可以正常启动，通过`df -T`查看，输出信息如下
```bash
Filesystem     Type     1K-blocks    Used Available Use% Mounted on
udev           devtmpfs    989476       0    989476   0% /dev
tmpfs          tmpfs       200248    1356    198892   1% /run
/dev/mmcblk0p8 ext4      61240644 1344444  56768600   3% /
tmpfs          tmpfs      1003484       0   1003484   0% /dev/shm
tmpfs          tmpfs         5120       8      5112   1% /run/lock
tmpfs          tmpfs       200696       0    200696   0% /run/user/1000
```
OverlayFS确实关闭了
